### PR TITLE
Add makefile that uses pattern matching strategy

### PR DESCRIPTION
**Pull request by milesfrain**
**Edit by Jordan:** Partially addresses #24 

Here's one makefile approach.

There are some options for command format. Currently using the first one:
* `make Template-run`
* `make runTemplate`
* etc...

### CODE REVIEW

**Comment by milesfrain** [comment]
Here's another option which is a bit simper, but has the following dowsides:
* Longer command due to passing `recipe` arg: `make recipe=Template run`
* Recursively calls `make` in a sloppy (non-idiomatic way) for `buildAllDev` / `buildAllProd`.

```make
# ------------- Common --------------

# Favor local npm devDependencies if they are installed
export PATH := node_modules/.bin:$(PATH)

# Use `PHONY` because target name is not an actual file
.PHONY: build info

# Builds everything. No recipe required.
# A build is necessary before parcel commands.
# Users could just run `spago build` instead of `make build`,
# unless they want local npm version and don't want to run `npx spago build`.
build:
	spago build

# Prints version and path information.
# For troubleshooting version mismatches.
info:
	which purs
	purs --version
	which spago
	spago version
	which parcel
	parcel --version

# Tests if recipe actually exists.
# This should be a dependency of all entry targets
recipes/%:
	test -d $* || { echo "Recipe $* does not exist"; exit 1;}

# ---------- `recpipe` strategy ----------------
#
# Example usage:
#
# make recipe=Template run
# make recipe=Template serve
# make recipe=Template buildDev
# make recipe=Template buildProd

# Helper-variables derived from `recipe` arg
main := $(recipe).Main
recipeDir := recipes/$(recipe)

devDir := $(recipeDir)/dev
devHtml := $(devDir)/index.html
devDistDir := $(recipeDir)/dev-dist

prodDir := $(recipeDir)/prod
prodHtml := $(prodDir)/index.html
prodJs := $(prodDir)/index.js
prodDistDir := $(recipeDir)/prod-dist

# Use `PHONY` because target name is not an actual file
.PHONY: run serve buildDev buildProd buildAllDev

# Runs recipe as node.js console app
run: $(recipeDir)
	spago run --main $(main)

# Launches recipe in browser
serve: $(recipeDir) build
	parcel $(devHtml) --out-dir $(devDistDir) --open

# Uses parcel to quickly create an unminified build.
# For CI purposes.
buildDev: export NODE_ENV=development
buildDev: $(recipeDir) build
	parcel build $(devHtml) --out-dir $(devDistDir) --no-minify --no-source-maps

$(prodDir):
	mkdir -p $(prodDir)

$(prodHtml): $(prodDir)
	cp $(devHtml) $(prodDir)

# Creates a minified production build.
# For reference.
buildProd: $(recipeDir) $(prodHtml)
	spago bundle-app --main $(main) --to $(prodJs)
	parcel build $(prodHtml) --out-dir $(prodDistDir)

# Creates all dev builds - for CI
buildAllDev:
	for d in recipes/*; do \
	    if [ -d $$d/dev ]; then \
	    	make recipe=$$(basename $$d) buildDev; \
	    fi \
	done

# Creates all prod builds - for CI
buildAllProd:
	for d in recipes/*; do \
	    if [ -d $$d/dev ]; then \
	    	make recipe=$$(basename $$d) buildProd; \
	    fi \
	done
```

**Comment by JordanMartinez** [comment]
First, thanks for figuring this out! I haven't used `make` before and I'm not very strong in `bash`.

> make Template-run

I like this approach to things. Less to type and it's pretty readable.

**Comment by JordanMartinez** [comment]
I think running just `make` should print the list of other scripts one could run (e.g. `make build` `make Template-*`, etc.). Then one could easily see all recipes that one could build as well as other things (e.g. clean, ci, help, etc.)

**Comment by milesfrain** [comment]
Sure. That addition should be pretty straightforward. Should we make that a separate task?

**Comment by JordanMartinez** [comment]
Seems like GNU make doesn't include a `list-scripts` task. I found [this SO answer](https://stackoverflow.com/a/26339924), but it doesn't work with our patterns approach. Here's the current output of `make` when `list` is the first rule using this PR:
```
$ make
build
buildAllDev
buildAllProd
info
recipesBuildDev
recipesBuildProd
recipes/RoutingHashHalogen
recipesRun
recipesServe
RoutingHashLog
RoutingPushHalogen
Template/prod
```

**Comment by milesfrain** [comment]
```makefile
.PHONY: list      
list:                 
  @echo === RECIPES ===
  @echo $(foreach r,$(recipes),$(r)-{run,serve}) | tr ' ' '\n'
```

Produces:
```
make list
=== RECIPES ===
RoutingHashHalogen-{run,serve}
RoutingHashLog-{run,serve}
RoutingPushHalogen-{run,serve}
Template-{run,serve}
```

Some additional logic can be added to determine whether `run` or `serve` are valid commands.

**Comment by JordanMartinez** [comment]
Well, let's add that version of the recipe list in, and then get this merged. I believe this will cause problems later, but let's take that risk for now, so we can continue iterating on other parts of this repo.

Since this is a simple fix, I'll merge this PR and then add that list myself afterwards.

**Pull request merged**
