### PR TITLE
Use pnpm for multi-package monorepo support with faster npm dependency downloads

### PR DESCRIPTION
**Pull request by JordanMartinez**
See [my comment in #56](https://github.com/JordanMartinez/purescript-cookbook/issues/56#issuecomment-647140196) for context.

We might want to try something other than `parcel` (e.g. `esbuild`) to see whether that's what causes `big-integers` to be added to the package.json file when `make BigInts-web` is run.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
[Here's the line](https://github.com/JordanMartinez/purescript-cookbook/issues/56#issuecomment-647140196) where `parcel` reports that it can't find the `big-integer` npm dependency. I doubt this because the same code builds find on the `Node.js` backend.

**Comment by milesfrain** [comment]
I'm reproducing this issue locally with:
```
pnpm install
make BigInts-node
make BigInts-web
```

I gave this a shot with parcel V2, and found tt doesn't play nice with pnpm yet https://github.com/parcel-bundler/parcel/issues/3408. It also wanted to add a `babel` devDependency.

We could try esbuild, although that requires some rework because we can't use `index.html` as an entry point https://github.com/evanw/esbuild/issues/31. We'd also need to setup something equivalent to parcel's `--open` flag.

I think the best option for now is to just add all npm dependencies to the top level `package.json` and make a note of the npm dependencies in each recipe's readme. #73 converts this PR to that strategy (I didn't want to push here in case we want to continue the pnpm investigation). We can revisit `parcel v2`, `esbuild`, and perhaps `webpack` if we run into issues with a single `package.json` and need to split them up per recipe. Hopefully some of the previously mentioned bundler issues are sorted-out by that time.

`pnpm` is nice, but let's hold off on making users install another tool unless we really need to. `npm install` in travis is fast enough so far ([~5 seconds](https://travis-ci.com/github/JordanMartinez/purescript-cookbook/builds/172534015#L209))

**Comment by JordanMartinez** [comment]
On my local computer, I tried changing to `esbuild` to see if that fixed the issue. **Unfortunately, it doesn't.** AFAICT, we have three choices:

First, we can figure out why the bundlers (i.e. parcel, esbuild) can't do what Node.js bundler (?) can and determine what to do from there. I'm not sure what the next step of this action would be and it may take a lot of time to figure out.

Second, add a constraint to this repo that all recipes that use `npm` dependencies must use the same versions of those dependencies. If Recipe A through Recipe Y wants to use version 1 and Recipe Z wants to use version 2 of npm dependency, Package, we have a few options. Let's assume Recipe A-Y already exists in the below options:
1. **if someone submitted a PR to add Recipe Z, close Recipe Z's PR.** This seems punitive and would likely discourage contributions, so I'm against it.
1. **if someone submitted a PR to add Recipe Z, force the person to also fix Recipes A-Y.** This seems like it would be fine if the number of recipes are small and it's an easy fix. However, if it requires updating a large number of recipes, it doesn't seem any better than the previous one.
1. in Recipe Z's PR, move Recipe Z into the `broken` folder and open an issue for fixing it later. This seems like a better solution because the cookbook will receive more up-to-date code. 

Third, we could remove the `recipes` folder entirely and push each recipe folder into the root folder. To distinguish recipe folders from non-recipe folders, we could prefix each one with `recipe-`.

**Comment by milesfrain** [comment]
> all recipes that use npm dependencies must use the same versions of those dependencies.

That sounds good.

If we do encounter mismatches, I think preference should go to whatever recipe/library uses the latest npm dependency version.

**Comment by JordanMartinez** [comment]
> I'm not following what advantages this offers.

On second thought, it doesn't fix the problem. Sorry about that.

> If we do encounter mismatches, I think preference should go to whatever recipe/library uses the latest npm dependency version. Older stuff can be moved to broken until the library, package-set, and recipe are updated.

Yeah, that was my thought as well.

> This might be something that should be enforced for package-sets, although I'm not sure if their CI is setup to check for this.

Hmm... that's a good point because how else would the package set maintain it's "they all compile together" guarantee? Is this being discussed on the registry repo yet?

> That sounds good.

I would prefer to find some way to achieve the outcomes I specified above. However, I think this cookbook is "good enough" for the time being. Let's open a new issue for that and further troubleshoot as time permits.

**Comment by JordanMartinez** [comment]
Closing as this PR's main purpose was to test how recipes that require npm dependencies should be handled.

**Pull request closed without merging**
