### PR TITLE
Add (try) links to Try PureScript demo for web recipes

### PR DESCRIPTION
**Pull request by milesfrain**
See table here: https://github.com/milesfrain/purescript-cookbook/blob/try-links/README.md#recipes

We can include some additional refinements to control whether to generate these links depending on whether the recipe is actually compatible with the try purescript environment.

Related to: https://github.com/purescript/trypurescript/pull/187

### CODE REVIEW

**Comment by milesfrain** [comment]
Looks like the react recipes could use some troubleshooting:
https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/CardsReactHooks/src/Main.purs
See error in dev console.

The halogen versions work fine https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/CardsHalogenHooks/src/Main.purs

**Comment by JordanMartinez** [comment]
Very nice!

I tried the above link and got this error:
```
bad result. Likely communication issue with compiler: POST compile response failed to decode: There was a problem making the request: AJAX request failed: POST https://compile.purescript.org/compile
```

**Comment by milesfrain** [comment]
I can't reproduce that compiler error. Could you try again, and if the issue persists, could we setup a screen share meeting for troubleshooting?

**Comment by JordanMartinez** [comment]
I can in fifteen minutes.

**Comment by JordanMartinez** [comment]
Nevermind. Turns out a browser extension (Privacy Badger in this case) was blocking the request.

**Comment by thomashoneyman** [comment]
> Nevermind. Turns out a browser extension (Privacy Badger in this case) was blocking the request.

That may be worth adding to the error message (a privacy extension may be blocking the request), as these extensions are increasingly common and strict.

**Pull request merged**
