### PR TITLE
Implemented the RunCapabilityPatternNode recipe

### LINKED ISSUE #265: RunCapabilityPatternNode
**Recipe Name**

```
RunCapabilityPatternNode
```

Each recipe name must be unique. Use PascalCase.

**Recipe Description**

What should this recipe do?

Similar to the existing CapabilityPatternNode recipe, but implemented using purescript-run and free monads

### PR DESCRIPTION
**Pull request by Mateiadrielrafael**
Closes #265 

Hope I didn't miss anything :D

### CODE REVIEW

**Comment by Mateiadrielrafael** [comment]
looks like I messed something up, since the ci failed, imma look into it tomorrow

**Comment by milesfrain** [comment]
I think you just need to run `make readme`. Also, let's get rid of that `.DS_Store` file.

**Comment by Mateiadrielrafael** [comment]
@milesfrain Thanks!

**Comment by JordanMartinez** [comment]
@Mateiadrielrafael Thanks for the PR!
In future PRs, please just push a new commit as opposed to force-pushing. It makes it easier to review the new changes you've made, especially since we squash the commits anyway.

**Comment by Mateiadrielrafael** [comment]
@JordanMartinez sorry 😅

**Pull request merged**
