### PR TITLE
Add cat gifs halogen

### PR DESCRIPTION
**Pull request by JordanMartinez**
Addresses part of #86

One problem. The URL used to get a cat GIF from giphy uses an API key. This is likely Elm's API key. We should get our own and use that as the link rather than theirs.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Also, should this recipe be renamed to `CatGifsHalogen`? I've mistyped the current name due to typing `GIF` followed by `s` followed by `H`.

**Comment by milesfrain** [comment]
That key is the "public beta key" so it's fine to use https://giphy.api-docs.io/1.0/welcome/access-and-api-keys

Leaning towards `Gif` over `GIF` due to ease of typing.

**Comment by JordanMartinez** [comment]
Ah, thanks for figuring that out!

Recipe has been renamed to `CatGifsHalogen`.

**Comment by paulyoung** [comment]
> The URL used to get a cat GIF from giphy uses an API key

Busted 😄 https://mobile.twitter.com/havemysecrets/status/1278682391108861953

**Comment by milesfrain** [comment]
They can have that secret

**Comment by JordanMartinez** [comment]
Nice! Free publicity!

**Pull request merged**
