### PR TITLE
Update package set to psc-0.13.8-20200716

### PR DESCRIPTION
**Pull request by JordanMartinez**
Update to package set was originally for `psc-0.13.8-20200708` but was later updated to `psc-0.13.8-20200708`

### CODE REVIEW

**Comment by milesfrain** [comment]
There was a breaking react-hooks change a few package set versions ago. Recently had to deal with this for the guide book. I'll fix the CI issue for this PR.

**Comment by milesfrain** [comment]
Looks like github is having a glitch. My push to this branch is not appearing in this issue. https://github.com/JordanMartinez/purescript-cookbook/commits/updatePackageSet

**Comment by JordanMartinez** [comment]
Weird... do you want to submit a new PR as a way to get around that issue?

**Comment by milesfrain** [comment]
My commit now appears in this PR.
Likely due to this incident https://www.githubstatus.com/incidents/j597fw8kv04c

**Comment by JordanMartinez** [comment]
> make ImagePreviewsHalogenHooks-build
> make CatGifsReactHooks-build

I fixed the Halogen one, but I'm not sure how to fix the React one. I know I need to use `mkAffReducer` somewhere, but I'm not sure where.

**Comment by milesfrain** [comment]
@ptrfrncsmrph for react recipe help

**Comment by JordanMartinez** [comment]
I decided to drop CatGifsReactHooks until @ptrfrncsmrph or another person figures out how to get it to build again.

**Comment by ptrfrncsmrph** [comment]
I should be able to look into it this weekend 🙂

**Pull request merged**
